name: 🐍 Python Auto Tagging
description: Automatically generate new tags when version file changes
author: Sam Morgan & Jorrick Sleijster
branding:
  icon: tag
  color: blue
inputs:
  token:
    description: Github Token
    required: true
  path:
    description: Path to version file
    required: true
  variable:
    description: Variable name containing version information
    required: true
  prefix:
    description: Prefix to add to the version tag
    required: false
  suffix:
    description: Suffix to add to the version tag
    required: false
  execute_entire_path:
    description: Execute entire path(1) or just the line starting with the variable name(0). Values can be 0 or 1.
    required: false
    default: "0"
outputs:
  version:
    description: The parsed version
  tag:
    description: The full tag name (e.g., v1.2.3)
  created:
    description: Whether a new tag was created
runs:
  using: docker
  image: Dockerfile
